# serviceName is the name of the service
serviceName:

# namespace the kubernetes namespace to deploy the chart to; this should usually be the modelforge namespace
namespace: "datvlcn"

# env is the environment the service is being deployed to; this should be one of 'qa', 'fsl', 'prd', or 'stg'
env: "qa"

# image is the container image to deploy
image:

# servicePort is the service port for the webserver; for message-based services, this is the port for the health check
servicePort: 8000

# cpuRequest is the cpu resource request for the service
cpuRequest: "50m"
# memoryRequest is the memory resource request for the service
memoryRequest: "500Mi"

# cpuLimit is the cpu resource limit for the service
cpuLimit: "1000m"
# memoryLimit is the memory resource limit for the service
memoryLimit: "1000Mi"

# minReplicaCount is the minimum number of replicas for the service
minReplicaCount: 1
# maxReplicaCount is the maximum number of replicas for the service
maxReplicaCount: 3

# autoscaleMessageCount is the number of messages that must be in the queue before autoscaling occurs
autoscaleMessageCount: 10
# servicebusPrefetchCount is the number of messages to prefetch from the service bus
servicebusPrefetchCount: 10
