# serviceName is the name of the service
serviceName:
# appVersion represents the version of the application deployed by the chart
appVersion: "0.0.0"

# namespace the kubernetes namespace to deploy the chart to; this should usually be the modelforge namespace
namespace:

# appPath supplies the argument passed to the uvicorn server worker on the image entrypoint
appPath: "app.main:app"

# env is the environment the service is being deployed to; this should be one of 'qa', 'fsl', 'prd', or 'stg'
env: "qa"

# image is the container image to deploy
image:

# ingressPath is the path for the ingress
ingressPath: "modelforge"

# servicePort is the service port for the webserver; for message-based services, this is the port for the health check
servicePort: 8000
# servicePortShort is the short service port for the webserver; for message-based services
servicePortShort: 80

# cpuRequest is the cpu resource request for the service
cpuRequest: "50m"
# memoryRequest is the memory resource request for the service
memoryRequest: "500Mi"

# cpuLimit is the cpu resource limit for the service
cpuLimit: "1000m"
# memoryLimit is the memory resource limit for the service
memoryLimit: "1000Mi"

# minReplicaCount is the minimum number of replicas for the service
minReplicaCount: 1
# maxReplicaCount is the maximum number of replicas for the service
maxReplicaCount: 3
