apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ .Values.namespace }}-secret-sb-connection
  namespace: {{ .Values.namespace }}
spec:
  vault:
    name: coyote-{{ .Values.env }}-keyvault
    object:
      name: {{ .Values.namespace }}-sb--connection
      type: secret
  output:
    secret:
      name: {{ .Values.namespace }}-secrets
      dataKey: sb--connection-string
